version: "3"

services:
  www:
    image: '${APP_NAME:-example}-www'
    container_name: '${APP_NAME:-example}-www'
    build:
      context: .
      dockerfile: docker/Dockerfile
    env_file:
      - docker/.docker.env
    volumes:
      - ./htdocs:/var/www/html
    ports:
      - ${PORT_PREFIX:-808}0:80
    depends_on:
      - 'mysql-db'
  mysql-db:
    container_name: '${APP_NAME:-example}-mysql'
    image: mysql:8.0
    volumes:
      - mysql-db:/var/lib/mysql
      - ./${MYSQL_IMPORT}:/docker-entrypoint-initdb.d/dump.sql
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - ${PORT_PREFIX:-808}3:3306
  phpmyadmin:
    # https://hub.docker.com/r/phpmyadmin/phpmyadmin/
    container_name: '${APP_NAME:-example}-phpmyadmin'
    image: 'phpmyadmin/phpmyadmin:latest'
    ports:
      - '${PORT_PREFIX:-808}1:80'
    environment:
      - 'PMA_HOST=mysql-db'
    depends_on:
      - 'mysql-db'
  mailhog:
    image: mailhog/mailhog
    container_name: '${APP_NAME:-example}-mailhog'
    ports:
      - 1025:1025 # smtp server
      - "${PORT_PREFIX:-808}2:8025" # web ui
volumes:
  mysql-db:
    driver: "local"