version: "3"

services:
  www:
    image: '${APP_NAME}-www'
    container_name: '${APP_NAME}-www'
    build:
      context: .
      dockerfile: docker/Dockerfile
    env_file:
      - docker/.docker.env
    volumes:
      - ./htdocs:/var/www/html
    ports:
      - ${PORT_PREFIX}80:80
    depends_on:
      - 'mysql-db'
  mysql-db:
    container_name: '${APP_NAME}-mysql'
    image: mysql:8.0
    volumes:
      - mysql-db:/var/lib/mysql
      - ./${MYSQL_IMPORT}:/docker-entrypoint-initdb.d/dump.sql
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - ${PORT_PREFIX}83:3306
  phpmyadmin:
    # https://hub.docker.com/r/phpmyadmin/phpmyadmin/
    container_name: '${APP_NAME}-phpmyadmin'
    image: 'phpmyadmin/phpmyadmin:latest'
    ports:
      - '${PORT_PREFIX}81:80'
    environment:
      - 'PMA_HOST=mysql-db'
    depends_on:
      - 'mysql-db'
  maildev:
    image: djfarrelly/maildev
    container_name: '${APP_NAME}-maildev'
    ports:
      - "${PORT_PREFIX}82:80"
volumes:
  mysql-db:
    driver: "local"